version: "3.7"
services:

  proxy-backend:
    image: envoyproxy/envoy:v1.21.0
    networks:
      echo-backend:
      echo-in-between:
        aliases:
        - proxy-postgres-backend.example.com
    command:
    - '-c'
    - '/etc/envoy.yaml'
    - '-l'
    - debug
    - '--log-path'
    - dev/stdout 
    ports:
    - "12345:12345"
    - "443:8080"
    volumes:
    - ./envoy-echo-cfg.yaml:/etc/envoy.yaml
    - ./certs/:/etc/certs/:ro

  proxy-nginx:
    image: nginx
    networks:
      echo-backend:
      echo-in-between:
        aliases:
        - proxy-postgres-backend.example.com
    ports:
    - "444:8081"
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./certs/:/etc/certs/:ro


  be-echo:
    image: kalmhq/echoserver
    ports:
    - 8001-8003:8001-8003
    networks:
      echo-backend:
      echo-in-between:
        aliases:
        - proxy-postgres-backend.example.com
    volumes:
    - ./certs/postgres-backend.example.com.crt:/workspace/default.pem:ro
    - ./certs/example.com.key:/workspace/default.key:ro


networks:

  echo-backend:
    name: echo-backend
  echo-in-between:
    name: echo-in-between
